### ISSUE TITLE
Terms and phrases

### ISSUE THREAD

**Issue by kitsao** [ilabafrica/rhtpt#17]
1. Use specific instructions for the buttons i.e Enable, change button 'approve' to 'view'.
2. The 'Deny' button in the modal for approving or Denying a participant access in the system should be changed t "Yes" or "No".
3. Users who have used the system before should be directed by a massage such as 'Please use your previous PT enrollment ID to login' in the modal that pops up instead of the current canceled.
4. In the approve user option, change confirm to enroll.
5. Check for contradictory terms e.g. cannot deactivate an inactive user.
6. Use Yes/No in pop-ups, avoid verbosity (can be handled in FAQs page).
7. Change Tester ID to Tester Enrollment ID.
8. TesterID/Username to be changed to PTEnrollmentID.
9. Replace NHRL with NPHL.

**Comment by kitsao** [comment]
Do away with 'The user will not be able to log in'.
The 'No' button on the 'Reject' pop-up does not dismiss the modal.
'Enroll' should for self-registered participants only.
TesterID/Username to be changed to PTEnrollmentID.
Replace NHRL with NPHL.

**Comment by Piusyo** [comment]
Username to be changed to Username/PTEnrollmentID.
The 'Deny' button in the modal for approving or Denying a participant access in the system should be changed t "Yes" or "No".
In the approve user option, change confirm to enroll.
Check for contradictory terms e.g. cannot deactivate an inactive user.
There are other various phrases raised to be unmeaningful but not covered here e.g, deny, approve, disable etc. Kindly exhaust them.

**Comment by winniebahati** [comment]
But all this has been covered.
