### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by kitsao** [ilabafrica/rhtpt#20]
1. Add narrative in the login page to direct the users.
2. In the forgotten password option, ask for Tester ID/PT Enrollment ID instead of email Address.
3. Show progress details while doing background processing e.g. uploading a worksheet.
4. User Address should be optional, in registration/Excel forms.
5. The Unique ID/Tester ID should be unedited and should be at the top (displaying participant details).
6. Reduce clatter on the display i.e. by displaying relevant data e.g. 'Gender' can be changed to 'facility' in participants page.
7. The Roles in the Edit user modal should be enabled for the administrator or just display the role of the user.
8. Logout option to be more visible, could be placed after 'reports' menu item.
9. Use visible colors in pop-ups e.g. in the register prompt, change grey to green.
10. Give direction in case of error pop-up e.g. for missing MFL during registration, ...contact your CHC/link to help desk to open ticket.
11. Sort list of users based on tester enrollment ID, ASC.
12. Narratives for different opo-up actions e.g. cancelling registration upon PT participation prompt, say 'by getting to this page, you're already registered, please retrieve your enrollment ID from past reports or CHC to proceed.
13. Check uneditable fields e.g. enrollment ID.

**Comment by winniebahati** [comment]
@KenMutuma there's an issue with the progress bar, review it.
Number 10 hasn't been covered.

@kitsao some issues raised here are abit similar to what I also had in Terms and Phrases. Like Number 12, it's just that the wordings are different. Number 4 too, except mine was to be optional in the registration form.
