### ISSUE TITLE
SMS notifications

### ISSUE THREAD

**Issue by annchemu** [ilabafrica/rhtpt#3]
1. SMS notifications should be follow Laravel's notification system.
2. Add 'reason for rejection' text field, SMS notifications for rejected users (reasons to be in the database for flexibility).
3. Include Tester ID in the rejection notification if reason for rejection is 'User already in the system'.
4. Send notifications for enabling/disabling user accounts.
5. More information to be added on the SMS verification.
6. The 'NHRL' found in the details of the SMS approval should be changed to 'NPHL'.
7. The header of the SMS verification should be changed from AFRICASTKNG to a meaningful one, initially Nat-HIVPT and the cost for changing it to be found out.

**Comment by kitsao** [comment]
Please check that the SMSHandler is applied to all instances where SMS notifications should be sent withn the controllers.
